//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalPrivado.DAO.WsGetMedicos {
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_os_ObtenerMedicoBinding", Namespace="urn:clinicauandes.org:ish.pm:obtenerMedico")]
    public partial class SI_os_ObtenerMedicoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_os_ObtenerMedicoOperationCompleted;
        
        /// <remarks/>
        public SI_os_ObtenerMedicoService() {
            this.Url = "http://qcpiqqas.clinicauandes.cl:50000/XISOAPAdapter/MessageServlet?senderParty=&" +
                "senderService=BC_PORTAL_WEB_115&receiverParty=&receiverService=&interface=SI_os_" +
                "ObtenerMedico&interfaceNamespace=urn%3Aclinicauandes.org%3Aish.pm%3AobtenerMedic" +
                "o";
        }
        
        public SI_os_ObtenerMedicoService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        public event SI_os_ObtenerMedicoCompletedEventHandler SI_os_ObtenerMedicoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_r_ObtenerMedico", Namespace="urn:clinicauandes.org:ish.pm:obtenerMedico")]
        public DT_r_ObtenerMedico SI_os_ObtenerMedico([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:clinicauandes.org:ish.pm:obtenerMedico")] DT_ObtenerMedico MT_ObtenerMedico) {
            object[] results = this.Invoke("SI_os_ObtenerMedico", new object[] {
                        MT_ObtenerMedico});
            return ((DT_r_ObtenerMedico)(results[0]));
        }
        
        /// <remarks/>
        public void SI_os_ObtenerMedicoAsync(DT_ObtenerMedico MT_ObtenerMedico) {
            this.SI_os_ObtenerMedicoAsync(MT_ObtenerMedico, null);
        }
        
        /// <remarks/>
        public void SI_os_ObtenerMedicoAsync(DT_ObtenerMedico MT_ObtenerMedico, object userState) {
            if ((this.SI_os_ObtenerMedicoOperationCompleted == null)) {
                this.SI_os_ObtenerMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_os_ObtenerMedicoOperationCompleted);
            }
            this.InvokeAsync("SI_os_ObtenerMedico", new object[] {
                        MT_ObtenerMedico}, this.SI_os_ObtenerMedicoOperationCompleted, userState);
        }
        
        private void OnSI_os_ObtenerMedicoOperationCompleted(object arg) {
            if ((this.SI_os_ObtenerMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_os_ObtenerMedicoCompleted(this, new SI_os_ObtenerMedicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:clinicauandes.org:ish.pm:obtenerMedico")]
    public partial class DT_ObtenerMedico {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_ObtenerMedicoDatosMedicos DatosMedicos;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:clinicauandes.org:ish.pm:obtenerMedico")]
    public partial class DT_ObtenerMedicoDatosMedicos {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutmed;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:clinicauandes.org:ish.pm:obtenerMedico")]
    public partial class DT_r_ObtenerMedico {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DatosMedicos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_r_ObtenerMedicoDatosMedicos[] DatosMedicos;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Errores;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:clinicauandes.org:ish.pm:obtenerMedico")]
    public partial class DT_r_ObtenerMedicoDatosMedicos {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string runmed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id_medico;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nommed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apemed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecnac;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string genero;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    public delegate void SI_os_ObtenerMedicoCompletedEventHandler(object sender, SI_os_ObtenerMedicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_os_ObtenerMedicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_os_ObtenerMedicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_r_ObtenerMedico Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_r_ObtenerMedico)(this.results[0]));
            }
        }
    }
}
