//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PortalPrivado.DAO.WsMenu {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_os_GetMenuBinding", Namespace="urn:Clinicauandes.org.ish.GetMenuPortal")]
    public partial class SI_os_GetMenuService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_os_GetMenuOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_os_GetMenuService() {
            this.Url = global::PortalPrivado.DAO.Properties.Settings.Default.PortalPrivado_DAO_WsMenu_SI_os_GetMenuService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_os_GetMenuCompletedEventHandler SI_os_GetMenuCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("MT_r_GetMenu", Namespace="urn:Clinicauandes.org.ish.GetMenuPortal")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Menu", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_r_GetMenuMenu[] SI_os_GetMenu([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:Clinicauandes.org.ish.GetMenuPortal")] DT_GetMenu MT_GetMenu) {
            object[] results = this.Invoke("SI_os_GetMenu", new object[] {
                        MT_GetMenu});
            return ((DT_r_GetMenuMenu[])(results[0]));
        }
        
        /// <remarks/>
        public void SI_os_GetMenuAsync(DT_GetMenu MT_GetMenu) {
            this.SI_os_GetMenuAsync(MT_GetMenu, null);
        }
        
        /// <remarks/>
        public void SI_os_GetMenuAsync(DT_GetMenu MT_GetMenu, object userState) {
            if ((this.SI_os_GetMenuOperationCompleted == null)) {
                this.SI_os_GetMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_os_GetMenuOperationCompleted);
            }
            this.InvokeAsync("SI_os_GetMenu", new object[] {
                        MT_GetMenu}, this.SI_os_GetMenuOperationCompleted, userState);
        }
        
        private void OnSI_os_GetMenuOperationCompleted(object arg) {
            if ((this.SI_os_GetMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_os_GetMenuCompleted(this, new SI_os_GetMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Clinicauandes.org.ish.GetMenuPortal")]
    public partial class DT_GetMenu {
        
        private string idMenuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdMenu {
            get {
                return this.idMenuField;
            }
            set {
                this.idMenuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Clinicauandes.org.ish.GetMenuPortal")]
    public partial class DT_r_GetMenuMenu {
        
        private string glosaField;
        
        private string idMenuField;
        
        private string uRLField;
        
        private string ordenField;
        
        private DT_r_GetMenuMenuSubMenu[] subMenuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Glosa {
            get {
                return this.glosaField;
            }
            set {
                this.glosaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdMenu {
            get {
                return this.idMenuField;
            }
            set {
                this.idMenuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubMenu", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_r_GetMenuMenuSubMenu[] SubMenu {
            get {
                return this.subMenuField;
            }
            set {
                this.subMenuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Clinicauandes.org.ish.GetMenuPortal")]
    public partial class DT_r_GetMenuMenuSubMenu {
        
        private string idSubMenuField;
        
        private string glosaSubMenuField;
        
        private string uRLField;
        
        private string ordenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdSubMenu {
            get {
                return this.idSubMenuField;
            }
            set {
                this.idSubMenuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GlosaSubMenu {
            get {
                return this.glosaSubMenuField;
            }
            set {
                this.glosaSubMenuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SI_os_GetMenuCompletedEventHandler(object sender, SI_os_GetMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_os_GetMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_os_GetMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_r_GetMenuMenu[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_r_GetMenuMenu[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591