//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalPrivado.DAO.WsInfoPac {
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_os_InfoPacienteBinding", Namespace="urn:Clinicauandes.org.ish.InfoPac")]
    public partial class SI_os_InfoPacienteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_os_InfoPacienteOperationCompleted;
        
        /// <remarks/>
        public SI_os_InfoPacienteService() {
            this.Url = "http://dcpiddev.clinicauandes.cl:50000/XISOAPAdapter/MessageServlet?senderParty=&" +
                "senderService=BC_PORTAL_WEB_115&receiverParty=&receiverService=&interface=SI_os_" +
                "InfoPaciente&interfaceNamespace=urn%3AClinicauandes.org.ish.InfoPac";
        }
        
        public SI_os_InfoPacienteService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        public event SI_os_InfoPacienteCompletedEventHandler SI_os_InfoPacienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_r_InfoPaciente", Namespace="urn:clinicauandes.org.ish.InfoPac")]
        public DT_r_InfoPaciente SI_os_InfoPaciente([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:clinicauandes.org.ish.InfoPac")] DT_InfoPaciente MT_InfoPaciente) {
            object[] results = this.Invoke("SI_os_InfoPaciente", new object[] {
                        MT_InfoPaciente});
            return ((DT_r_InfoPaciente)(results[0]));
        }
        
        /// <remarks/>
        public void SI_os_InfoPacienteAsync(DT_InfoPaciente MT_InfoPaciente) {
            this.SI_os_InfoPacienteAsync(MT_InfoPaciente, null);
        }
        
        /// <remarks/>
        public void SI_os_InfoPacienteAsync(DT_InfoPaciente MT_InfoPaciente, object userState) {
            if ((this.SI_os_InfoPacienteOperationCompleted == null)) {
                this.SI_os_InfoPacienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_os_InfoPacienteOperationCompleted);
            }
            this.InvokeAsync("SI_os_InfoPaciente", new object[] {
                        MT_InfoPaciente}, this.SI_os_InfoPacienteOperationCompleted, userState);
        }
        
        private void OnSI_os_InfoPacienteOperationCompleted(object arg) {
            if ((this.SI_os_InfoPacienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_os_InfoPacienteCompleted(this, new SI_os_InfoPacienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Clinicauandes.org.ish.InfoPac")]
    public partial class DT_InfoPaciente {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdPac;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Clinicauandes.org.ish.InfoPac")]
    public partial class DT_r_InfoPaciente {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombre;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SegundoNom;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AppPat;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AppMat;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaNacimiento;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Direccion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Telefono1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Telefono2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Libre1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Libre2;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    public delegate void SI_os_InfoPacienteCompletedEventHandler(object sender, SI_os_InfoPacienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.5.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_os_InfoPacienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_os_InfoPacienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_r_InfoPaciente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_r_InfoPaciente)(this.results[0]));
            }
        }
    }
}
