//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalPrivado.DAO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dcpiddev.clinicauandes.cl:50000/XISOAPAdapter/MessageServlet?senderParty=&" +
            "senderService=BC_PORTAL_WEB_115&receiverParty=&receiverService=&interface=SI_os_" +
            "GetMenu&interfaceNamespace=urn%3AClinicauandes.org.ish.GetMenuPortal")]
        public string PortalPrivado_DAO_WsMenu_SI_os_GetMenuService {
            get {
                return ((string)(this["PortalPrivado_DAO_WsMenu_SI_os_GetMenuService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dcpiddev.clinicauandes.cl:50000/XISOAPAdapter/MessageServlet?senderParty=&" +
            "senderService=BC_PORTAL_WEB_115&receiverParty=&receiverService=&interface=Si_os_" +
            "GetEspecialidad&interfaceNamespace=urn%3AClinicauandes.org.ish.GetEspecialidades" +
            "")]
        public string PortalPrivado_DAO_WsGetEspecialidad_Si_os_GetEspecialidadService {
            get {
                return ((string)(this["PortalPrivado_DAO_WsGetEspecialidad_Si_os_GetEspecialidadService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dcpiddev.clinicauandes.cl:50000/XISOAPAdapter/MessageServlet?senderParty=&" +
            "senderService=BC_PORTAL_WEB_115&receiverParty=&receiverService=&interface=Si_os_" +
            "busqueda&interfaceNamespace=urn%3AClinicauandes.org.GetBusquedapredic")]
        public string PortalPrivado_DAO_WsGetBusqueda_Si_os_busquedaService {
            get {
                return ((string)(this["PortalPrivado_DAO_WsGetBusqueda_Si_os_busquedaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dcpiddev.clinicauandes.cl:50000/XISOAPAdapter/MessageServlet?senderParty=&" +
            "senderService=BC_PORTAL_WEB_115&receiverParty=&receiverService=&interface=SI_Bus" +
            "carCita_os&interfaceNamespace=urn%3Aclinicauandes.org%3Aish.pm%3Abuscarcita")]
        public string PortalPrivado_DAO_WsBuscarCita_SI_BuscarCita_osService {
            get {
                return ((string)(this["PortalPrivado_DAO_WsBuscarCita_SI_BuscarCita_osService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dcpiddev.clinicauandes.cl:50000/XISOAPAdapter/MessageServlet?senderParty=&" +
            "senderService=BC_PORTAL_WEB_115&receiverParty=&receiverService=&interface=SI_Dis" +
            "pDiariaxMedico_os&interfaceNamespace=urn%3Aclinicauandes.org%3Aish.pm%3Adispdiar" +
            "iaxmedico")]
        public string PortalPrivado_DAO_WsDispDiaria_SI_DispDiariaxMedico_osService {
            get {
                return ((string)(this["PortalPrivado_DAO_WsDispDiaria_SI_DispDiariaxMedico_osService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dcpiddev.clinicauandes.cl:50000/XISOAPAdapter/MessageServlet?senderParty=&" +
            "senderService=BC_PORTAL_WEB_115&receiverParty=&receiverService=&interface=SI_Dis" +
            "pMensualxMedico_os&interfaceNamespace=urn%3Aclinicauandes.org%3Aish.pm%3Adispmen" +
            "sualxmedico")]
        public string PortalPrivado_DAO_WsDispMensual_SI_DispMensualxMedico_osService {
            get {
                return ((string)(this["PortalPrivado_DAO_WsDispMensual_SI_DispMensualxMedico_osService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dcpiddev.clinicauandes.cl:50000/XISOAPAdapter/MessageServlet?senderParty=&" +
            "senderService=BC_PORTAL_WEB_115&receiverParty=&receiverService=&interface=SI_Res" +
            "ervaCita_os&interfaceNamespace=urn%3Aclinicauandes.org%3Aish.pm%3Areservacita")]
        public string PortalPrivado_DAO_WsReserva_SI_ReservaCita_osService {
            get {
                return ((string)(this["PortalPrivado_DAO_WsReserva_SI_ReservaCita_osService"]));
            }
        }
    }
}
