//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PortalPrivado.DAO.WsReserva {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_ReservaCita_osBinding", Namespace="urn:clinicauandes.org:ish.pm:reservacita")]
    public partial class SI_ReservaCita_osService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_ReservaCita_osOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_ReservaCita_osService() {
            this.Url = global::PortalPrivado.DAO.Properties.Settings.Default.PortalPrivado_DAO_WsReserva_SI_ReservaCita_osService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_ReservaCita_osCompletedEventHandler SI_ReservaCita_osCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_r_ReservaCita", Namespace="urn:clinicauandes.org:ish.pm:reservacita")]
        public DT_r_ReservaCita SI_ReservaCita_os([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:clinicauandes.org:ish.pm:reservacita")] DT_ReservaCita MT_ReservaCita) {
            object[] results = this.Invoke("SI_ReservaCita_os", new object[] {
                        MT_ReservaCita});
            return ((DT_r_ReservaCita)(results[0]));
        }
        
        /// <remarks/>
        public void SI_ReservaCita_osAsync(DT_ReservaCita MT_ReservaCita) {
            this.SI_ReservaCita_osAsync(MT_ReservaCita, null);
        }
        
        /// <remarks/>
        public void SI_ReservaCita_osAsync(DT_ReservaCita MT_ReservaCita, object userState) {
            if ((this.SI_ReservaCita_osOperationCompleted == null)) {
                this.SI_ReservaCita_osOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_ReservaCita_osOperationCompleted);
            }
            this.InvokeAsync("SI_ReservaCita_os", new object[] {
                        MT_ReservaCita}, this.SI_ReservaCita_osOperationCompleted, userState);
        }
        
        private void OnSI_ReservaCita_osOperationCompleted(object arg) {
            if ((this.SI_ReservaCita_osCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_ReservaCita_osCompleted(this, new SI_ReservaCita_osCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:clinicauandes.org:ish.pm:reservacita")]
    public partial class DT_ReservaCita {
        
        private string rutsolField;
        
        private string nompacField;
        
        private string apepatpacField;
        
        private string telefonoField;
        
        private string mailField;
        
        private string rutpacField;
        
        private string fecreservaField;
        
        private string horareservaField;
        
        private string codorigenField;
        
        private string medicoField;
        
        private string utratamientoField;
        
        private string especialidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutsol {
            get {
                return this.rutsolField;
            }
            set {
                this.rutsolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nompac {
            get {
                return this.nompacField;
            }
            set {
                this.nompacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apepatpac {
            get {
                return this.apepatpacField;
            }
            set {
                this.apepatpacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutpac {
            get {
                return this.rutpacField;
            }
            set {
                this.rutpacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecreserva {
            get {
                return this.fecreservaField;
            }
            set {
                this.fecreservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horareserva {
            get {
                return this.horareservaField;
            }
            set {
                this.horareservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codorigen {
            get {
                return this.codorigenField;
            }
            set {
                this.codorigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string medico {
            get {
                return this.medicoField;
            }
            set {
                this.medicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string utratamiento {
            get {
                return this.utratamientoField;
            }
            set {
                this.utratamientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:clinicauandes.org:ish.pm:reservacita")]
    public partial class DT_r_ReservaCita {
        
        private string codreservaField;
        
        private string fechacitaField;
        
        private string horacitaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codreserva {
            get {
                return this.codreservaField;
            }
            set {
                this.codreservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechacita {
            get {
                return this.fechacitaField;
            }
            set {
                this.fechacitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horacita {
            get {
                return this.horacitaField;
            }
            set {
                this.horacitaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SI_ReservaCita_osCompletedEventHandler(object sender, SI_ReservaCita_osCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_ReservaCita_osCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_ReservaCita_osCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_r_ReservaCita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_r_ReservaCita)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591