//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PortalPrivado.DAO.WsBuscarCita {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_BuscarCita_osBinding", Namespace="urn:clinicauandes.org:ish.pm:buscarcita")]
    public partial class SI_BuscarCita_osService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_BuscarCita_osOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_BuscarCita_osService() {
            this.Url = global::PortalPrivado.DAO.Properties.Settings.Default.PortalPrivado_DAO_WsBuscarCita_SI_BuscarCita_osService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_BuscarCita_osCompletedEventHandler SI_BuscarCita_osCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_r_BuscarCita", Namespace="urn:clinicauandes.org:ish.pm:buscarcita")]
        public DT_r_BuscarCita SI_BuscarCita_os([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:clinicauandes.org:ish.pm:buscarcita")] DT_BuscarCita MT_BuscarCita) {
            object[] results = this.Invoke("SI_BuscarCita_os", new object[] {
                        MT_BuscarCita});
            return ((DT_r_BuscarCita)(results[0]));
        }
        
        /// <remarks/>
        public void SI_BuscarCita_osAsync(DT_BuscarCita MT_BuscarCita) {
            this.SI_BuscarCita_osAsync(MT_BuscarCita, null);
        }
        
        /// <remarks/>
        public void SI_BuscarCita_osAsync(DT_BuscarCita MT_BuscarCita, object userState) {
            if ((this.SI_BuscarCita_osOperationCompleted == null)) {
                this.SI_BuscarCita_osOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_BuscarCita_osOperationCompleted);
            }
            this.InvokeAsync("SI_BuscarCita_os", new object[] {
                        MT_BuscarCita}, this.SI_BuscarCita_osOperationCompleted, userState);
        }
        
        private void OnSI_BuscarCita_osOperationCompleted(object arg) {
            if ((this.SI_BuscarCita_osCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_BuscarCita_osCompleted(this, new SI_BuscarCita_osCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:clinicauandes.org:ish.pm:buscarcita")]
    public partial class DT_BuscarCita {
        
        private DT_BuscarCitaBuscaOfertaGral buscaOfertaGralField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_BuscarCitaBuscaOfertaGral BuscaOfertaGral {
            get {
                return this.buscaOfertaGralField;
            }
            set {
                this.buscaOfertaGralField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:clinicauandes.org:ish.pm:buscarcita")]
    public partial class DT_BuscarCitaBuscaOfertaGral {
        
        private string idmedField;
        
        private string codespField;
        
        private string codisaField;
        
        private string fechaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idmed {
            get {
                return this.idmedField;
            }
            set {
                this.idmedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codesp {
            get {
                return this.codespField;
            }
            set {
                this.codespField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codisa {
            get {
                return this.codisaField;
            }
            set {
                this.codisaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:clinicauandes.org:ish.pm:buscarcita")]
    public partial class DT_r_BuscarCita {
        
        private DT_r_BuscarCitaBuscaOfertaGral[] buscaOfertaGralField;
        
        private string erroresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BuscaOfertaGral", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_r_BuscarCitaBuscaOfertaGral[] BuscaOfertaGral {
            get {
                return this.buscaOfertaGralField;
            }
            set {
                this.buscaOfertaGralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:clinicauandes.org:ish.pm:buscarcita")]
    public partial class DT_r_BuscarCitaBuscaOfertaGral {
        
        private string rutmedField;
        
        private string nommedField;
        
        private string apepatField;
        
        private string apematField;
        
        private string fechaField;
        
        private string especialidadField;
        
        private string id_medicoField;
        
        private string id_especialidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutmed {
            get {
                return this.rutmedField;
            }
            set {
                this.rutmedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nommed {
            get {
                return this.nommedField;
            }
            set {
                this.nommedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apepat {
            get {
                return this.apepatField;
            }
            set {
                this.apepatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apemat {
            get {
                return this.apematField;
            }
            set {
                this.apematField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id_medico {
            get {
                return this.id_medicoField;
            }
            set {
                this.id_medicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id_especialidad {
            get {
                return this.id_especialidadField;
            }
            set {
                this.id_especialidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SI_BuscarCita_osCompletedEventHandler(object sender, SI_BuscarCita_osCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_BuscarCita_osCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_BuscarCita_osCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_r_BuscarCita Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_r_BuscarCita)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591