//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PortalPrivado.DAO.WsDispMensual {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_DispMensualxMedico_osBinding", Namespace="urn:clinicauandes.org:ish.pm:dispmensualxmedico")]
    public partial class SI_DispMensualxMedico_osService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_DispMensualxMedico_osOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_DispMensualxMedico_osService() {
            this.Url = global::PortalPrivado.DAO.Properties.Settings.Default.PortalPrivado_DAO_WsDispMensual_SI_DispMensualxMedico_osService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_DispMensualxMedico_osCompletedEventHandler SI_DispMensualxMedico_osCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_r_DispMensualxMedico", Namespace="urn:clinicauandes.org:ish.pm:dispmensualxmedico")]
        public DT_r_DispMensualxMedico SI_DispMensualxMedico_os([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:clinicauandes.org:ish.pm:dispmensualxmedico")] DT_DispMensualxMedico MT_DispMensualxMedico) {
            object[] results = this.Invoke("SI_DispMensualxMedico_os", new object[] {
                        MT_DispMensualxMedico});
            return ((DT_r_DispMensualxMedico)(results[0]));
        }
        
        /// <remarks/>
        public void SI_DispMensualxMedico_osAsync(DT_DispMensualxMedico MT_DispMensualxMedico) {
            this.SI_DispMensualxMedico_osAsync(MT_DispMensualxMedico, null);
        }
        
        /// <remarks/>
        public void SI_DispMensualxMedico_osAsync(DT_DispMensualxMedico MT_DispMensualxMedico, object userState) {
            if ((this.SI_DispMensualxMedico_osOperationCompleted == null)) {
                this.SI_DispMensualxMedico_osOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_DispMensualxMedico_osOperationCompleted);
            }
            this.InvokeAsync("SI_DispMensualxMedico_os", new object[] {
                        MT_DispMensualxMedico}, this.SI_DispMensualxMedico_osOperationCompleted, userState);
        }
        
        private void OnSI_DispMensualxMedico_osOperationCompleted(object arg) {
            if ((this.SI_DispMensualxMedico_osCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_DispMensualxMedico_osCompleted(this, new SI_DispMensualxMedico_osCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:clinicauandes.org:ish.pm:dispmensualxmedico")]
    public partial class DT_DispMensualxMedico {
        
        private DT_DispMensualxMedicoBuscaOfertaMedica buscaOfertaMedicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_DispMensualxMedicoBuscaOfertaMedica BuscaOfertaMedica {
            get {
                return this.buscaOfertaMedicaField;
            }
            set {
                this.buscaOfertaMedicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:clinicauandes.org:ish.pm:dispmensualxmedico")]
    public partial class DT_DispMensualxMedicoBuscaOfertaMedica {
        
        private string idmedField;
        
        private string fechaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idmed {
            get {
                return this.idmedField;
            }
            set {
                this.idmedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:clinicauandes.org:ish.pm:dispmensualxmedico")]
    public partial class DT_r_DispMensualxMedico {
        
        private DT_r_DispMensualxMedicoBuscaOfertaMedica[] buscaOfertaMedicaField;
        
        private string erroresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BuscaOfertaMedica", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_r_DispMensualxMedicoBuscaOfertaMedica[] BuscaOfertaMedica {
            get {
                return this.buscaOfertaMedicaField;
            }
            set {
                this.buscaOfertaMedicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:clinicauandes.org:ish.pm:dispmensualxmedico")]
    public partial class DT_r_DispMensualxMedicoBuscaOfertaMedica {
        
        private string fecateField;
        
        private string horateField;
        
        private string estadoField;
        
        private string utratamientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecate {
            get {
                return this.fecateField;
            }
            set {
                this.fecateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horate {
            get {
                return this.horateField;
            }
            set {
                this.horateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Utratamiento {
            get {
                return this.utratamientoField;
            }
            set {
                this.utratamientoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SI_DispMensualxMedico_osCompletedEventHandler(object sender, SI_DispMensualxMedico_osCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_DispMensualxMedico_osCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_DispMensualxMedico_osCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_r_DispMensualxMedico Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_r_DispMensualxMedico)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591