//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PortalPrivado.DAO.WsDispDiaria {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_DispDiariaxMedico_osBinding", Namespace="urn:clinicauandes.org:ish.pm:dispdiariaxmedico")]
    public partial class SI_DispDiariaxMedico_osService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_DispDiariaxMedico_osOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_DispDiariaxMedico_osService() {
            this.Url = global::PortalPrivado.DAO.Properties.Settings.Default.PortalPrivado_DAO_WsDispDiaria_SI_DispDiariaxMedico_osService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_DispDiariaxMedico_osCompletedEventHandler SI_DispDiariaxMedico_osCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_r_DispDiariaxMedico", Namespace="urn:clinicauandes.org:ish.pm:dispdiariaxmedico")]
        public DT_r_DispDiariaxMedico SI_DispDiariaxMedico_os([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:clinicauandes.org:ish.pm:dispdiariaxmedico")] DT_DispDiariaxMedico MT_DispDiariaxMedico) {
            object[] results = this.Invoke("SI_DispDiariaxMedico_os", new object[] {
                        MT_DispDiariaxMedico});
            return ((DT_r_DispDiariaxMedico)(results[0]));
        }
        
        /// <remarks/>
        public void SI_DispDiariaxMedico_osAsync(DT_DispDiariaxMedico MT_DispDiariaxMedico) {
            this.SI_DispDiariaxMedico_osAsync(MT_DispDiariaxMedico, null);
        }
        
        /// <remarks/>
        public void SI_DispDiariaxMedico_osAsync(DT_DispDiariaxMedico MT_DispDiariaxMedico, object userState) {
            if ((this.SI_DispDiariaxMedico_osOperationCompleted == null)) {
                this.SI_DispDiariaxMedico_osOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_DispDiariaxMedico_osOperationCompleted);
            }
            this.InvokeAsync("SI_DispDiariaxMedico_os", new object[] {
                        MT_DispDiariaxMedico}, this.SI_DispDiariaxMedico_osOperationCompleted, userState);
        }
        
        private void OnSI_DispDiariaxMedico_osOperationCompleted(object arg) {
            if ((this.SI_DispDiariaxMedico_osCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_DispDiariaxMedico_osCompleted(this, new SI_DispDiariaxMedico_osCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:clinicauandes.org:ish.pm:dispdiariaxmedico")]
    public partial class DT_DispDiariaxMedico {
        
        private DT_DispDiariaxMedicoBuscaOfertaMedica buscaOfertaMedicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_DispDiariaxMedicoBuscaOfertaMedica BuscaOfertaMedica {
            get {
                return this.buscaOfertaMedicaField;
            }
            set {
                this.buscaOfertaMedicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:clinicauandes.org:ish.pm:dispdiariaxmedico")]
    public partial class DT_DispDiariaxMedicoBuscaOfertaMedica {
        
        private string idmedField;
        
        private string fechaField;
        
        private string especialidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idmed {
            get {
                return this.idmedField;
            }
            set {
                this.idmedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:clinicauandes.org:ish.pm:dispdiariaxmedico")]
    public partial class DT_r_DispDiariaxMedico {
        
        private DT_r_DispDiariaxMedicoBuscaOfertaMedica[] buscaOfertaMedicaField;
        
        private string erroresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BuscaOfertaMedica", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_r_DispDiariaxMedicoBuscaOfertaMedica[] BuscaOfertaMedica {
            get {
                return this.buscaOfertaMedicaField;
            }
            set {
                this.buscaOfertaMedicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Errores {
            get {
                return this.erroresField;
            }
            set {
                this.erroresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:clinicauandes.org:ish.pm:dispdiariaxmedico")]
    public partial class DT_r_DispDiariaxMedicoBuscaOfertaMedica {
        
        private string fecateField;
        
        private string horateField;
        
        private string estadoField;
        
        private string utratamientoField;
        
        private string especialidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecate {
            get {
                return this.fecateField;
            }
            set {
                this.fecateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horate {
            get {
                return this.horateField;
            }
            set {
                this.horateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Utratamiento {
            get {
                return this.utratamientoField;
            }
            set {
                this.utratamientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SI_DispDiariaxMedico_osCompletedEventHandler(object sender, SI_DispDiariaxMedico_osCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_DispDiariaxMedico_osCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_DispDiariaxMedico_osCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_r_DispDiariaxMedico Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_r_DispDiariaxMedico)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591