//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalPrivado.Web {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalPrivado.Web.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr&gt;
        ///                        &lt;td style=&quot;border-top: 2px solid #fff; border-right: 1px solid #BFC8CC; background: #F7F7F7; color: #616A71; font-size: 14px; font-weight: normal; padding: 4px;&quot;&gt;{0} &lt;/td&gt;
        ///                        &lt;td style=&quot;border-top: 2px solid #fff; border-right: 1px solid #BFC8CC; background: #F7F7F7; color: #616A71; font-size: 14px; font-weight: normal; padding: 4px;&quot;&gt;{1}&lt;/td&gt;
        ///                        &lt;td style=&quot;border-top: 2px solid #fff; border-right: 1px solid #BFC8CC; background: #F7F7 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CuerpoHtml {
            get {
                return ResourceManager.GetString("CuerpoHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a phormazabal@clinicauandes.cl.
        /// </summary>
        internal static string emailsend {
            get {
                return ResourceManager.GetString("emailsend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;Mi Plan&lt;/title&gt;
        ///	&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#ffffff&quot; leftmargin=&quot;0&quot; marginheight=&quot;0&quot; marginwidth=&quot;0&quot; topmargin=&quot;0&quot; style=&quot;font-family: &apos;Roboto&apos;, sans-serif; color: #616A71; font-size: 14px;line-height: 20px;&quot;&gt;
        ///
        ///&lt;table width=&quot;800&quot; border=&quot;0&quot; align=&quot;center&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;padding: 40px 0;&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;&lt;im [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;Mi Plan&lt;/title&gt;
        ///	&lt;link href=&quot;https://fonts.googleapis.com/css?family=Roboto:400,700&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#ffffff&quot; leftmargin=&quot;0&quot; marginheight=&quot;0&quot; marginwidth=&quot;0&quot; topmargin=&quot;0&quot; style=&quot;font-family: &apos;Roboto&apos;, sans-serif; color: #616A71; font-size: 14px;line-height: 20px;&quot;&gt;
        ///
        ///&lt;table width=&quot;800&quot; border=&quot;0&quot; align=&quot;center&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;padding: 40px 0;&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;&lt;im [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HtmlExamenes {
            get {
                return ResourceManager.GetString("HtmlExamenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clinica20201.
        /// </summary>
        internal static string passSend {
            get {
                return ResourceManager.GetString("passSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://172.16.2.35:90/.
        /// </summary>
        internal static string UrlAgendaPublica {
            get {
                return ResourceManager.GetString("UrlAgendaPublica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://172.16.2.25:90/reserva-de-horas.
        /// </summary>
        internal static string UrlInicio {
            get {
                return ResourceManager.GetString("UrlInicio", resourceCulture);
            }
        }
    }
}
