//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalPrivado.Web {
	
	
	public partial class ReservaHora {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.ScriptManager ScriptManager2;
		
		protected System.Web.UI.UpdatePanel UpdatePanel1;
		
		protected System.Web.UI.WebControls.HiddenField hdRut;
		
		protected System.Web.UI.WebControls.TextBox txtbus;
		
		protected System.Web.UI.WebControls.Button Button1;
	}
}
